INSERT INTO country (country_name)
VALUES ('Afghanistan'),
       ('Albania'),
       ('Algeria'),
       ('Andorra'),
       ('Angola'),
       ('Antigua and Barbuda'),
       ('Argentina'),
       ('Armenia'),
       ('Australia'),
       ('Austria'),
       ('Azerbaijan'),
       ('Bahamas'),
       ('Bahrain'),
       ('Bangladesh'),
       ('Barbados'),
       ('Belarus'),
       ('Belgium'),
       ('Belize'),
       ('Benin'),
       ('Bhutan'),
       ('Bolivia'),
       ('Bosnia and Herzegovina'),
       ('Botswana'),
       ('Brazil'),
       ('Brunei'),
       ('Bulgaria'),
       ('Burkina Faso'),
       ('Burundi'),
       ('Cabo Verde'),
       ('Cambodia'),
       ('Cameroon'),
       ('Canada'),
       ('Central African Republic'),
       ('Chad'),
       ('Chile'),
       ('China'),
       ('Colombia'),
       ('Comoros'),
       ('Congo (Congo-Brazzaville)'),
       ('Costa Rica'),
       ('Croatia'),
       ('Cuba'),
       ('Cyprus'),
       ('Czechia (Czech Republic)'),
       ('Denmark'),
       ('Djibouti'),
       ('Dominica'),
       ('Dominican Republic'),
       ('Ecuador'),
       ('Egypt'),
       ('El Salvador'),
       ('Equatorial Guinea'),
       ('Eritrea'),
       ('Estonia'),
       ('Eswatini (fmr. Swaziland)'),
       ('Ethiopia'),
       ('Fiji'),
       ('Finland'),
       ('France'),
       ('Gabon'),
       ('Gambia'),
       ('Georgia'),
       ('Germany'),
       ('Ghana'),
       ('Greece'),
       ('Grenada'),
       ('Guatemala'),
       ('Guinea'),
       ('Guinea-Bissau'),
       ('Guyana'),
       ('Haiti'),
       ('Holy See'),
       ('Honduras'),
       ('Hungary'),
       ('Iceland'),
       ('India'),
       ('Indonesia'),
       ('Iran'),
       ('Iraq'),
       ('Ireland'),
       ('Israel'),
       ('Italy'),
       ('Jamaica'),
       ('Japan'),
       ('Jordan'),
       ('Kazakhstan'),
       ('Kenya'),
       ('Kiribati'),
       ('Korea (North)'),
       ('Korea (South)'),
       ('Kuwait'),
       ('Kyrgyzstan'),
       ('Laos'),
       ('Latvia'),
       ('Lebanon'),
       ('Lesotho'),
       ('Liberia'),
       ('Libya'),
       ('Liechtenstein'),
       ('Lithuania'),
       ('Luxembourg'),
       ('Madagascar'),
       ('Malawi'),
       ('Malaysia'),
       ('Maldives'),
       ('Mali'),
       ('Malta'),
       ('Marshall Islands'),
       ('Mauritania'),
       ('Mauritius'),
       ('Mexico'),
       ('Micronesia'),
       ('Moldova'),
       ('Monaco'),
       ('Mongolia'),
       ('Montenegro'),
       ('Morocco'),
       ('Mozambique'),
       ('Myanmar (Burma)'),
       ('Namibia'),
       ('Nauru'),
       ('Nepal'),
       ('Netherlands'),
       ('New Zealand'),
       ('Nicaragua'),
       ('Niger'),
       ('Nigeria'),
       ('North Macedonia'),
       ('Norway'),
       ('Oman'),
       ('Pakistan'),
       ('Palau'),
       ('Palestine State'),
       ('Panama'),
       ('Papua New Guinea'),
       ('Paraguay'),
       ('Peru'),
       ('Philippines'),
       ('Poland'),
       ('Portugal'),
       ('Qatar'),
       ('Romania'),
       ('Russia'),
       ('Rwanda'),
       ('Saint Kitts and Nevis'),
       ('Saint Lucia'),
       ('Saint Vincent and the Grenadines'),
       ('Samoa'),
       ('San Marino'),
       ('Sao Tome and Principe'),
       ('Saudi Arabia'),
       ('Senegal'),
       ('Serbia'),
       ('Seychelles'),
       ('Sierra Leone'),
       ('Singapore'),
       ('Slovakia'),
       ('Slovenia'),
       ('Solomon Islands'),
       ('Somalia'),
       ('South Africa'),
       ('South Sudan'),
       ('Spain'),
       ('Sri Lanka'),
       ('Sudan'),
       ('Suriname'),
       ('Sweden'),
       ('Switzerland'),
       ('Syria'),
       ('Tajikistan'),
       ('Tanzania'),
       ('Thailand'),
       ('Timor-Leste'),
       ('Togo'),
       ('Tonga'),
       ('Trinidad and Tobago'),
       ('Tunisia'),
       ('Turkey'),
       ('Turkmenistan'),
       ('Tuvalu'),
       ('Uganda'),
       ('Ukraine'),
       ('United Arab Emirates'),
       ('United Kingdom'),
       ('United States of America'),
       ('Uruguay'),
       ('Uzbekistan'),
       ('Vanuatu'),
       ('Venezuela'),
       ('Vietnam'),
       ('Yemen'),
       ('Zambia'),
       ('Zimbabwe');

INSERT INTO media_format (media_format_name, borrow_duration_days)
VALUES ('book', '28'),
       ('e-book', '28'),
       ('video', '14'), -- lesson, course, video
       ('dvd_film', '14'),
       ('board_game', '28');

INSERT INTO creator_role (role_name)
VALUES ('director'),
       ('author'),
       ('translator'),
       ('director'),
       ('compositor'),
       ('co-author');

INSERT INTO language (language_name)
VALUES ('English'),
       ('Mandarin Chinese'),
       ('Hindi'),
       ('Spanish'),
       ('French'),
       ('Arabic'),
       ('Bengali'),
       ('Russian'),
       ('Portuguese'),
       ('Urdu'),
       ('Indonesian'),
       ('German'),
       ('Japanese'),
       ('Swahili'),
       ('Marathi'),
       ('Telugu'),
       ('Turkish'),
       ('Korean'),
       ('Tamil'),
       ('Vietnamese'),
       ('Italian'),
       ('Arabic (Egyptian)'),
       ('Punjabi'),
       ('Javanese'),
       ('Hindu'),
       ('Filipino'),
       ('German (Swiss)'),
       ('Wu Chinese'),
       ('Vietnamese (Northern)'),
       ('Turkish (Cypriot)'),
       ('Kurdish'),
       ('Gujarati'),
       ('Polish'),
       ('Ukrainian'),
       ('Yoruba'),
       ('Amharic'),
       ('Malay'),
       ('Persian'),
       ('Pashto'),
       ('Korean (North)'),
       ('Kannada'),
       ('Assamese'),
       ('Nepali'),
       ('Sinhala'),
       ('Khmer'),
       ('Hausa'),
       ('Zulu'),
       ('Serbo-Croatian'),
       ('Icelandic'),
       ('Bhojpuri'),
       ('Maithili'),
       ('Chichewa');

INSERT INTO language_type(language_type_name)
values ('original'),
       ('translation'),
       ('subtitles'),
       ('dubbing');

INSERT INTO library (library_name)
values ('name of library 1'),
       ('name of library 2'),
       ('name of library 3'),
       ('name of library 4'),
       ('name of library 5');

INSERT INTO library_address(library_id, city, street, house_number, osm_link)
VALUES (1, 'Berlin', 'Street One', 1, 'dummy'),
       (2, 'Berlin', 'Street Two', 2, 'dummy'),
       (3, 'Berlin', 'Street Tree', 3, 'dummy'),
       (4, 'Berlin', 'Street Four', 4, 'dummy'),
       (5, 'Berlin', 'Street Five', 5, 'dummy');